- hosts: localhost
  tasks:
    - debug:
        msg: Starting installing the tools...

- name: apt update/upgrade
  import_playbook: playbooks/unix/apt.yaml

- name: Install git
  import_playbook: playbooks/unix/git.yaml

- name: Install pip
  import_playbook: playbooks/unix/pip.yaml

- name: Install ssh
  import_playbook: playbooks/unix/ssh.yaml

- name: Install vim
  import_playbook: playbooks/unix/vim.yaml

- name: Install zsh
  import_playbook: playbooks/unix/zsh.yaml
