- hosts: localhost
  tasks:
    - debug:
        msg: Starting installing the tools...

- name: apt update/upgrade
  import_playbook: playbooks/unix/apt.yaml

- name: Install git
  import_playbook: playbooks/unix/git.yaml

- name: Install pip
  import_playbook: playbooks/unix/pip.yaml
