---
- name: Update and Upgrade APT Packages
  hosts: localhost
  become: yes

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Update apt and install required system packages
      apt:
        pkg:
          - wget
          - htop
          - unzip
          - curl
          - vim
          - git
          - ufw
          - openssh-server
          - nginx
          - python3
          - python3-pip
          - nodejs
          - npm
          - ruby
          - gem
          - docker.io
          - docker-compose
        state: latest
        update_cache: true
