---
- name: Install git
  hosts: localhost
  become: yes
  tasks:
    - name: Apdate packages
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Get git version
      command: git --version
      register: git_version

    - name: Show pip version
      debug:
        var: git_version.stdout
